development:
  adapter: postgresql
  database: development
  username: sushil
  password: theodore
  host: localhost

test:
  adapter: postgresql
  database: test
  username: sushil
  password: theodore
  host: localhost

production:
  adapter: postgresql
  database: production
  username: sushil
  password: theodore
  host: localhost